name: krom_script
description: A lightweight, embeddable scripting language for Dart applications.
version: 1.0.3
homepage: https://github.com/issadicko/krom-lang
repository: https://github.com/issadicko/krom-lang
issue_tracker: https://github.com/issadicko/krom-lang/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  path: ^1.9.0
